### ISSUE TITLE
c++

### ISSUE THREAD

**Issue by qizq1337** [Itroublve/AntiSteal.NET#4]
why no c++ now i cry

**Comment by XxDarknedxX** [comment]
Cuz the grabber rules says
Rule #1 No C++
Rule #2 No qizq
Rule #3 No skidtools users (im just kidding if you're seeing this tech lol)

**Comment by qizq1337** [comment]
> Cuz the grabber rules says
> 
> Rule #1 No C++
> 
> Rule #2 No qizq
> 
> Rule #3 No skidtools users (im just kidding if you're seeing this tech lol) 

there are many grabbers in c++

if you want i can make anti steal in c++

**Comment by Itroublve** [comment]
> > Cuz the grabber rules says
> > 
> > Rule #1 No C++
> > 
> > Rule #2 No qizq
> > 
> > Rule #3 No skidtools users (im just kidding if you're seeing this tech lol) 
> 
> there are many grabbers in c++
> 
> if you want i can make anti steal in c++

If you wanna do it, then feel free too. I unfortunately don't know/nor have the time to learn CPP. And currently I got school so I'm very busy with school and other private projects.
